const Koa = require('koa')
const bodyParser = require('koa-bodyparser')
const static = require('koa-static')
const { connectMongoose } = require('./app/db')
const InitManager = require('./core/init')
const { handleException } = require('./middlewares/handelException')
const { config } = require('./config/config')
connectMongoose().then(()=>{
    const app = new Koa()
    // 全局异常处理
    app.use(handleException)
    app.use(bodyParser())
    app.use(static(config.staticPath))
    InitManager.init(app)
    app.listen(3000)
})